steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/charismatic-web-466508-n9/legal-ai-assistant', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/charismatic-web-466508-n9/legal-ai-assistant']

  # Deploy the container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'legal-ai-assistant'
      - '--image'
      - 'gcr.io/charismatic-web-466508-n9/legal-ai-assistant'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/charismatic-web-466508-n9/legal-ai-assistant'